[package]
name = "evops-grpc"
edition = "2024"

[dependencies]
evops-core = { workspace = true }
evops-types = { workspace = true }

axum = { workspace = true }
# Needed by build.rs.
http = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
tonic-web = { workspace = true }
tower-http = { workspace = true, features = ["cors"] }

[build-dependencies]
eyre = { workspace = true }
tonic-build = { workspace = true }

[lints]
workspace = true
