[package]
name = "script-dummy-data"
edition = "2024"

[dependencies]
evops-pb = { workspace = true }

color-eyre = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tonic = { workspace = true }

[lints]
workspace = true
