[package]
name = "evops-core"
edition = "2024"

[dependencies]
evops-db = { workspace = true }
evops-types = { workspace = true }

eyre = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
url = { workspace = true }

[lints]
workspace = true
