[package]
name = "evops-core"
edition = "2024"

[dependencies]
evops-db = { workspace = true }

eyre = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync"] }
url = { workspace = true }

[lints]
workspace = true
